Added Provider-Specific timeouts
GIScience/orstools-qgis-plugin pull request #121
Opened 2020-10-12 14:23 UTC by jannefleischer

For calculation of big Matrixes on our custom ORS-Server I needed more calculation time, so I included a new provider-specific timeout int orstools.

It is still a little bit ugly as I used some unnecessary recasting int/string for seconds-values...

2021-04-29 16:18 UTC, koebi requested changes
Hey,

thank you very much for your pull request, it is greatly appreciated :))
Sorry for the long silence from our side :(

I think sticking to a default of 60 seconds as a timeout is great, but should be consistently used everywhere.
This could be made clear by setting a `placeholderText()` to `60` in `timeout_text`, such that users see that a default is set.
This default would be used by using `provider.get('timeout', 60)` rather than provider['timeout'].

I think this would simplify a lot of things :) 

Best regards,
Jakob



This would enable us to drop a bunch of `timeout`s in the code,

2021-04-29 16:18 UTC, koebi commented on ORStools/common/networkaccessmanager.py
> +    def __init__(self, authid=None, disable_ssl_certificate_validation=False, exception_class=None, debug=True, timeout=None):
default to 60 here should work :)

2021-06-14 13:15 UTC, koebi commented
Hey @jannefleischer,

it's been over a month since the review, so I wanted to follow up on this :)
Given our response time, your inactivity is definitely excused :smile:
I just wanted to know whether you plan on working on this any time soon.

If you don't want to or simply don't have the time, just let us know so we can move forward with this :)

Best regards,
Jakob

2021-06-14 17:19 UTC, jannefleischer commented
Sorry for the major lag in response time. At the moment I can't see when there is time once again for this. But currently I am overwhelmed by other work, so sadly, I can't promise anything :(

2021-12-08 13:44 UTC, koebi commented
This has been reworked slightly and merged in 7ce0407b1925d39b5aa2961f24014f8067523451. Thank you very much for your work, glad to finally see this happen :)

2021-12-08 13:44 UTC, closed without merging