Add roundtrip option to Traveling Salesman
GIScience/orstools-qgis-plugin pull request #146
Opened 2021-06-02 15:38 UTC by koebi

This will also rename `Optimize Start`, `Optimize End` and `None` to `Fix Start`, `Fix End` and `Fix Both` for clarification.
The tooltips are adapted slightly to explain the actual behaviour.

2021-06-08 14:01 UTC, TheGreatRefrigerator requested changes
For https://github.com/GIScience/orstools-qgis-plugin/pull/146/commits/6bd00af73366ddf5f00c5d9a852d80dec2bef951
i would also add the changelog.md and metadata.txt entries

2021-06-08 14:04 UTC, TheGreatRefrigerator commented on ORStools/gui/ORStoolsDialogUI.py
> +import resources_rc
I used the following command in the `ORStools/gui` folder:
`pyuic5 -o ORStoolsDialogUI.py ORStoolsDialogUI.ui `

2021-06-10 12:18 UTC, koebi commented
We decided on updating `metadata.txt` only when releasing, right?

2021-06-11 13:41 UTC, TheGreatRefrigerator commented on ORStools/gui/ORStoolsDialogUI.py
> +import resources_rc
Finally got it to work by using the actual packages from qgis instead of installing the missing packages globally -.-

2021-06-11 13:43 UTC, TheGreatRefrigerator commented on ORStools/gui/ORStoolsDialogUI.py
> +# Created by: PyQt5 UI code generator 5.15.2
We should use the version from the latest QGIS we are developing on (e.g. 3.16 LTR currently) which is `5.14.1`

2021-06-11 13:44 UTC, TheGreatRefrigerator commented
I have restructured the branch a bit:
- rebased on master
- fixed roundtrip to round_trip
- combined small fix commits
- added metadata.txt entry
- enhanced commit messages ;)

2021-06-11 13:57 UTC, TheGreatRefrigerator approved these changes

2021-06-11 13:58 UTC, merged