Add snapping endpoint
GIScience/orstools-qgis-plugin pull request #267
Opened 2024-06-10 09:10 UTC by merydian

2024-06-10 09:11 UTC, merydian commented
Translation is still missing.

2024-07-04 17:33 UTC, merydian commented
Advanced parameters still need to be removed.

2024-10-31 11:42 UTC, MichaelsJP commented
@merydian What is the status of this?

2024-10-31 13:09 UTC, merydian commented
Translation is missing and there are merge conflicts, which are simple to solve though. Except for that it's ready for a review. 1-2h of work I think.

2025-05-08 12:31 UTC, koebi commented
Looks good so far :)

Snapping from a point layer needs some way to reference the original points, otherwise it's hard to see what got snapped where.

2025-05-08 12:58 UTC, koebi requested changes
Translation is missing.

2025-05-08 12:58 UTC, koebi commented on ORStools/help/snap_from_point.help
> +The snapping endpoint can be used to snap points to the edges of the street network for a specific means of transportation.
```suggestion
The snapping endpoint can be used to snap points which are not on a road to the road network for a specific means of transportation.
```

2025-05-08 12:58 UTC, koebi commented on ORStools/help/snap_from_point_de.help
> +Der Snap-Algorithmus kann verwendet werden, um Punkte an den Rändern des Straßennetzes für ein bestimmtes Verkehrsmittel zu finden.
…hier hat doch die automatische Übersetzung zugeschlagen!

2025-05-08 12:58 UTC, koebi commented on ORStools/help/snap_from_point_layer_de.help
> +Der Snap-Algorithmus kann verwendet werden, um Punkte an den Rändern des Straßennetzes für ein bestimmtes Verkehrsmittel zu finden.
s.o.

2025-05-08 13:14 UTC, merydian commented on ORStools/utils/processing.py
> +        if location:
I think sometimes the response contains empty points if the respective point couldn't be snapped.

2025-05-08 14:07 UTC, koebi requested changes
Minor comments on the german translation.

Do we have tests, btw?

2025-05-08 14:07 UTC, koebi commented on ORStools/help/snap_from_point_de.help
> +Mit dem Snapping-Endpunkt können Punkte, die sich nicht auf einer Straße befinden, für ein bestimmtes Verkehrsmittel an das Straßennetz angepasst werden.
```suggestion
Mit dem Snapping-Endpunkt können Punkte, die sich nicht auf einer Straße befinden, für ein bestimmtes Verkehrsmittel auf dem Straßennetz eingerastet werden.
```

2025-05-08 14:07 UTC, koebi commented on ORStools/help/snap_from_point_layer_de.help
> +Mit dem Snapping-Endpunkt können Punkte, die sich nicht auf einer Straße befinden, für ein bestimmtes Verkehrsmittel an das Straßennetz angepasst werden.
```suggestion
Mit dem Snapping-Endpunkt können Punkte, die sich nicht auf einer Straße befinden, für ein bestimmtes Verkehrsmittel auf dem Straßennetz eingerastet werden.
```

2025-05-09 07:39 UTC, koebi approved these changes

2025-05-09 09:38 UTC, koebi requested changes
Feedback from look-and-feel-Test:
1. Layer Field "NAME" should probably be "road_name" or "snapped_name" or the like - as that is what is recorded there
2. 
```
warning:/home/jschnell/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ORStools/proc/snap_layer_proc.py:99: DeprecationWarning: QgsField constructor is deprecated
              sink_fields.append(QgsField("SNAPPED_DISTANCE", QVariant.Double))
```
3. same warning for "NAME"-field

2025-05-09 09:47 UTC, merydian commented on ORStools/proc/snap_point_proc.py
> +        sink_fields.append(QgsField("SNAPPED_DISTANCE", QVariant.Double))
The original value is kept. 

Should we do "SNAPPED_NAME", and if someone already has a layer with that field abort the process and log an error? I think dynamic name creation could create inconsistencies which would be problematic for automating this process etc.

2025-05-09 11:01 UTC, koebi commented on ORStools/proc/snap_point_proc.py
> +        sink_fields.append(QgsField("SNAPPED_DISTANCE", QVariant.Double))
Ah, true.
Yeah, "SNAPPED_NAME" sounds good for now, and from my POV we could also transfer the rest to an issue and tackle it separately, as I think there should be other algos with a similar problem?

2025-05-09 11:23 UTC, merydian commented on ORStools/proc/snap_point_proc.py
> +        sink_fields.append(QgsField("SNAPPED_DISTANCE", QVariant.Double))
I was thinking the same :+1:

2025-05-12 07:30 UTC, takb approved these changes
LGTM

2025-05-12 07:34 UTC, takb commented on ORStools/help/snap_from_point_de.help
> +Der Snap-Algorithmus kann verwendet werden, um Punkte an den Rändern des Straßennetzes für ein bestimmtes Verkehrsmittel zu finden.
@merydian will address later

2025-05-12 07:35 UTC, merged