Make vertices draggable and droppable
GIScience/orstools-qgis-plugin pull request #268
Opened 2024-06-10 13:56 UTC by merydian

This includes all new changes, makes #222 obsolete, closes #204 and is related to #206.

2024-07-22 09:58 UTC, TheGreatRefrigerator commented
Hey @merydian you leaked your API key in this branch. Best remove it from the commit, force push to the branch, delete the key from your account and create a new one :)

2024-11-11 15:42 UTC, MichaelsJP commented
Incredible work @merydian !

Only comment from my side, it would be cool if the preview feature can work on an existing list of points when toggled. 

- When enabled, the route preview is generated on the set points. 
- When disabled, the points remain but switch to the default flight of the crow representation.

2024-11-15 07:51 UTC, koebi commented
Hey,
I played around with this on QGIS 3.34.12, these are my findings so far:
* Toggling `LivePreview` when no valid provider is set deletes all nodes.
* Once a list is "final" (i.e. once I have double-clicked), is there a way to drag/drop nodes? I haven't found one…
* The MapTool doesn't switch back after double-clicking. I figured that was fixed at some point?

2024-11-22 14:06 UTC, koebi requested changes
Two more general comments:
* on profile change, the preview should be re-generated
* tests are missing.

As for the translation:
As usually, you can provide the `tr()`-functions, I will provide the translation.

2024-11-22 14:06 UTC, koebi commented on ORStools/gui/ORStoolsDialog.py
> +    def change_cursor_on_hover(self, pos):
It feels like these functions (change_cursor_on_hover, check_annotation_hover, _on_movetool_map_press, _on_movetool_map_release, create_rubber_band, create_vertex) should all be part of the line_tool?

Instead, the rubber band has been moved to the main UI - what is the reason for this?

2024-11-22 14:06 UTC, koebi commented on ORStools/gui/ORStoolsDialog.py
> +            Use a different point closer to a road.""",
Translation missing

2024-11-22 14:08 UTC, koebi commented
Moreover, we should look at getting this combined with the ESC/Right-Click feat merged yesterday.

2025-05-08 12:03 UTC, koebi commented
* make radius for "grabbing" points bigger
* clearer documentation (see #308 )
* numbering of points gets messed up when adding points after having deleted points.
* fix `wayoints` typo in tooltip

2025-05-09 09:49 UTC, koebi requested changes

2025-05-09 09:49 UTC, koebi commented on ORStools/gui/ORStoolsDialog.py
>          else:
This is a change that I think would lend itself nicely to red-green-testing:

The error description is "numbering of points gets messed up when adding points after having deleted points".

Thus, we could write a test that:
1. adds some points
2. deletes a point
3. adds another point
4. checks the numbering of the points.

We should see that test fail - so we commit, stating why it fails
We then fix the issue, as is done here
We should then see that test succeed - so we commit, stating what we fixed :)

2025-05-09 09:49 UTC, koebi commented on ORStools/utils/maptools.py
> +        self.click_dist = 25
I think this is where a nice commit message might improve things, as someone might be unsure why 25 was chosen here, and the commit message explaining this, along the lines of "we had 10 for testing, was too small, chose 25 as it felt better" would make it clearer that there is no deep reasoning behind the number - and if there is, the commit message could explain *that*.

2025-05-09 11:23 UTC, koebi requested changes

2025-05-09 11:23 UTC, koebi commented on tests/test_gui.py
> +        print("laokdndfla" + str(numbers))
Überbleibsel aus der Entwicklung?

2025-05-09 11:23 UTC, koebi commented on tests/test_gui.py
> +        self.assertTrue(ordered)
Ich würde die Variable in das Assert-Statement reinziehen?

2025-05-09 11:23 UTC, koebi commented on tests/test_gui.py
>          # Check rubber band has only 2 vertices
I feel the comment is wrong?

2025-05-09 11:29 UTC, merged