Add export endpoint
GIScience/orstools-qgis-plugin pull request #269
Opened 2024-07-06 19:38 UTC by merydian

Extent choosable via [QgsProcessingParameterExtent](https://qgis.org/pyqgis/3.34/core/QgsProcessingParameterExtent.html).

2024-07-06 19:39 UTC, merydian commented
Should we wait for this to be available in the public API?

2024-07-06 19:40 UTC, merydian commented
Translation still missing.

2024-09-13 08:45 UTC, koebi requested changes
Looking good so far :)

Translation is missing @koebi

2024-09-13 08:45 UTC, koebi commented on ORStools/proc/export_proc.py
> +                from_coords = self.get_location_by_id(from_id, response["nodes"])
This iterates all nodes twice for every edge, taking what is in theory a linear operation and making it quadratic.

I think it makes sense to parse nodes into a dict to look up coordinates easily.

2024-09-18 13:12 UTC, koebi commented
After testing for a bit, I think it makes sense to also export nodes into a separate layer - it's a bit too tricky from my perspective to correctly parse them from the edge layer.

2024-10-18 14:09 UTC, koebi approved these changes

2024-10-18 14:13 UTC, merged